### PR TITLE
Fix #67 drag/drop not working on touch devices

### LINKED ISSUE #26: Hammerjs: compatibility and improved gesture support
I recently found that tableDnD would not work with [hammer.js](http://eightmedia.github.io/hammer.js/) also enabled as it modifies the properties of the event we rely upon for drag and drop implementation.

This poses an issue that needs to be addressed but perhaps considering hammer as a dependency instead would be a more favourable option which would minimize our own adaptation for gesture implementation and widen our overall device compatibility while supporting a project which has taken this task on themselves at the same time.

Alternatively we would still have to consider the presence of hammer which becomes a messy proposition.

@isocra The former sounds like win win to me, any thoughts, concerns and suggestions?

### LINKED ISSUE #67: Windows 10, Chrome
Drag/Drop won't work at all in Chrome on Windows 10.  Edge works fine.

Any ideas on how to get this working on Chrome?

### PR DESCRIPTION
**Pull request by fappels**
Bind to both touchstart and mousedown events

### CODE REVIEW

**Comment by brendon** [comment]
Hi @fappels, can you give some more details on this. What browsers are still broken with this issue?

**Comment by fappels** [comment]
Hi @brendon, chrome and firefox, you can find more details in issue #67 .

**Comment by brendon** [comment]
Thanks @fappels, I've had a look through this and it looks ok to me. I get what you're doing now.

One question: Is it possible that both `touchstart` and `mousedown` get triggered on a touch device at the same time when it's a touch? I had a feeling that mouse events were emulated on iOS Safari in addition to touch events. Have you tested on that platform?

Check out: https://stackoverflow.com/questions/13655919/how-to-bind-both-mousedown-and-touchstart-but-not-respond-to-both-android-jqu

**Comment by fappels** [comment]
Seems it was already fixed by https://github.com/isocra/TableDnD/commit/b89aea3ee74d4872f02484dffa85b5dfac7b2aa7
Didn't notice, you can close issue #67 . Thanks for looking into my PR.

About the testing, tested above commit on android chrome, android old stock browser, ios 10.3 safari, all fine.

The stackoverflow toppic is outdated. Chome 55+ ignores preventDefault(), https://www.chromestatus.com/features/5093566007214080

**Comment by brendon** [comment]
Thanks @fappels :) Were you using an old version of DnD? Just interested to know how you noticed the problem in the first place?

I'll close #67 :)

**Comment by fappels** [comment]
Thanks @brendon, yes I first did the patch on 0.6, because newer versions did not work on our project. When I saw you patched the jquery 3 issue, I started transferring my patch to the master but didn't notice the patch with the double events (didn't know you can add more event listeners at the same time with jquery bind command).  Are you planning to create a new distribution version with the jquery 3 patch?

**Comment by brendon** [comment]
Ah I see :) I've not done a distribution of this project before so I'm not sure how it works. @isocra, could you walk me through it?

**Comment by isocra** [comment]
@brendon: Good idea!

**Comment by brendon** [comment]
Sweet :) Ready when you are :)

**Comment by fappels** [comment]
Any news on creating the new distribution version ;)

**Comment by brendon** [comment]
Hi @fappels, @isocra and I have preliminarily emailed each other about it. Just looking at wether we also switch to NPM and yarn away from bower.

**Comment by isocra** [comment]
Hi @fappels and @brendon, I've made a new branch `candidate/v1_0` for the candidate release. I've also published the package to npm.

In the branch, I've fixed some jsHint errors and warnings (mostly replaced `==` with `===`), it wanted some bigger changes, but I didn't want to do them at this time as I haven't got the time to thoroughly test it on all platforms.

Is there any chance @fappels, you could check out the version in this branch and test it in your set-up? Thanks!!

I'm also hoping to do some more work on the README and GitHubPages...

**Comment by brendon** [comment]
Thanks @isocra :) Is there anything I can do to help?

**Comment by isocra** [comment]
@brendon, yes please!! If you had the chance to check it on your rig too that'd be great (I've checked Chrome, Safari and Firefox on Mac and I shouldl be able to test it on IE and Edge over the next few days, but what I don't have is any way to test touch, either on tablets, or a Windows touch screen--so anyone at all reading this, feel free to test!!). 

You can install it in a temp directory using `npm install tablednd`. Then user testing is as easy as cd-ing into `node_modules/tablednd` and then opening `index.html`. There are test cases for most of the features (I think).

I'm going to spend a few mins trying to make the docs better (both README.md and the GitHub Pages), but anything you want to add to that would be great.

Also I've added an npm badge to `README.md` but it doesn't show the version. I don't know whether that's because `package.json` isn't in `master` or just because I haven't got the syntax right. Any thoughts?

Finally I haven't looked at yarn yet, but that's probably not too urgent. We can raise a separate issue for that.

Thanks!

**Comment by fappels** [comment]
@isocra thanks for making the v1.0 branch. I asked to merge the RC in our setup current alpha version so more people cant test. Now you make a new branch, we have houndci-bot watching and detected misleading code reading warnings. If you like to solve them for the new branch, you can find them here: https://github.com/Dolibarr/dolibarr/pull/7780#discussion_r151937670

**Comment by isocra** [comment]
Hi @fappels, I had a look at the issues from houndci (I've also now enabled houndci for TableDnD which will hopefully help us in the future) and I don't really agree with its criticism that complex lines shouldn't have breaks on `||` or `&&` (in fact JSHint is going to remove it, see http://jshint.com/docs/options/#laxbreak). 

I had disabled that rule in my jshint config in Grunt, but obviously houndci doesn't know that. So, for now, I've put the jshint config options directly in the file. 

Could you have a go with the latest version and see if hound barks less?

Thanks!

**Comment by fappels** [comment]
@isocra Hound now only barked on unchanged minified file. Maybe we need to add a .hound.yml to our setup.

**Comment by isocra** [comment]
@fappels, yes I think you probably do. You should be able to add a jshint section, you might also need to add a `.jshintrc` file and possibly a `.jshintignore` file too. I have found the documentation not particularly helpful, but these resources might be good:

* http://jshint.com/docs/cli/ 
* https://gist.github.com/bolshchikov/10016245

Feel free to make a PR against our `candidate/v1_0` branch if you find a good config that works!!

**Comment by brendon** [comment]
Hi @isocra, I do really want to assist but just letting you know that I'm full-up on a contract job at the moment. Hopefully I'll be able to find some time in the next couple of weeks. I only have a mac here too, and no access to a touchscreen desktop though I hear it's possible to emulate that in chrome with a tweak to the config. It'd be ideal if we could tweak the config in headless-chrome and automate that particular test.

I'll also look into yarn for you too though that'll be my very first foray even into just using it full-stop :) Fingers crossed :D

**Pull request closed without merging**
