### PR TITLE
Create 404.html

### PR DESCRIPTION
**Pull request by Kundan28**

### CODE REVIEW

**Comment by Kundan28** [comment]
@brendon It will replace the default 404 error page and we can make that page more attractive.

**Comment by Kundan28** [comment]
No, it's different from that.

**Comment by Kundan28** [comment]
No, it's different from that.

**Comment by brendon** [comment]
So for the Github Pages tablelDnD site then? I'm just a bit confused as to why you've created this PR.

**Comment by Kundan28** [comment]
If you like to keep that GitHub pages one then you can close this PR.

**Comment by Kundan28** [comment]
If you like to keep that GitHub pages one then you can close this PR.

**Comment by brendon** [comment]
Thanks @Kundan28, I'm happy to look into merging this but I just don't understand where this 404 file will be used? It doesn't make any sense to me. I need you to be more descriptive about the problem you're trying to solve.

**Pull request closed without merging**
