### PR TITLE
Solved: Issue with getPosition #102

### PR DESCRIPTION
**Pull request by pirobox**
https://github.com/isocra/TableDnD/issues/102

### CODE REVIEW

**Comment by brendon** [comment]
I can confirm this works on the latest Safari. @isocra are you happy to have this merged and if so, are you able to release a new version? :)

**Comment by isocra** [comment]
Hi @brendon and @pirobox,

Thanks for doing this. Go ahead and merge it and then I'll make a new release.

**Comment by brendon** [comment]
Thanks @isocra, all done :)

**Comment by brendon** [comment]
Hi @isocra, is there any chance you could push this latest version into npm?

Also, your package.json `main` key points at `Gruntfile.js`. It should point at the current javascript file instead. That way people can just `import "tablednd"` and it'll load correctly.

**Comment by isocra** [comment]
Hi @brendon, I've now published v1.0.5 fixing the `main` reference in `package.json`. Otherwise, though, the javascript seems to be the same as 1.0.4. Or have I missed something?

**Comment by brendon** [comment]
Sorry, I didn't notice that 1.0.4 was already out there :)

Yep, that's the only change :) Thanks for this! :D

**Comment by brendon** [comment]
Ah I remember now, the problem was that 1.0.4 wasn't actually in NPM for some reason :D 1.0.5 is so that's all good :)

**Pull request merged**
